#ifndef SECRETS_HEADER_FILE_H
#define SECRETS_HEADER_FILE_H

const char *WIFI_SSID = "YOUR_WIFI_SSID";
const char *WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

const char *APPLICATION_KEY = "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH";
const char *API_KEY = "0dead000-beef-0000-0000-000000000000";
const char *MAC_ADDRESS = "80:AA:BB:CC:CC:CC";

#endif /* SECRETS_HEADER_FILE_H */
